import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import SyncDatabase from '../../sqlite/sync-database'
import type { DispatchLifecycleIncidentRecord } from '../domain/dispatch-lifecycle-incident'
import { migrateExecutionStore } from './execution-schema'
import { SqliteDispatchLifecycleIncidentStore } from './sqlite-dispatch-lifecycle-incident-store'

// ORCA-S4 SPEC §8.4, §14 LIFE-9 — dispatch_lifecycle_incident is the S4-ONLY
// incident channel (never settlement_incident / worktree_provenance_incident),
// and the ONLY S4 table classified PROJECTION (a rebuild drops + recreates it).
// UNIQUE(correlation_id, kind, evidence_digest); a retry on the same evidence is
// a no-op. RED: `./sqlite-dispatch-lifecycle-incident-store` does not exist yet.

function incident(over: Partial<DispatchLifecycleIncidentRecord> = {}): DispatchLifecycleIncidentRecord {
  return {
    id: 'inc_1',
    correlationId: 'corr_1',
    orcaDispatchId: 'ctx_1',
    sliceRef: 'ORCA-S4',
    kind: 'process_identity_mismatch',
    evidenceDigest: 'h'.repeat(64),
    detailJson: '{"observed":true}',
    blocked: true,
    resolvedAt: null,
    resolutionNote: null,
    raisedAt: '2026-09-13T00:00:00Z',
    ...over
  }
}

describe('SqliteDispatchLifecycleIncidentStore (§8.4, PROJECTION)', () => {
  const dirs: string[] = []
  afterEach(() => {
    while (dirs.length) {
      try {
        rmSync(dirs.pop()!, { recursive: true, force: true, maxRetries: 3 })
      } catch {
        /* best-effort */
      }
    }
  })
  function open() {
    const dir = mkdtempSync(join(tmpdir(), 'orca-s4-dli-'))
    dirs.push(dir)
    const db = new SyncDatabase(join(dir, 'exec.db'))
    db.pragma('foreign_keys = OFF')
    migrateExecutionStore(db)
    return { db, store: new SqliteDispatchLifecycleIncidentStore(db) }
  }

  it('insert returns { inserted: true } and the row is readable by slice', () => {
    const { store } = open()
    expect(store.insert(incident())).toEqual({ inserted: true })
    expect(store.listBySlice('ORCA-S4')).toHaveLength(1)
  })

  it('a retry with the SAME (correlation_id, kind, evidence_digest) is a no-op: inserted:false, no second row (§8.4 "never auto-resolved")', () => {
    const { store } = open()
    store.insert(incident())
    expect(store.insert(incident({ id: 'inc_2', detailJson: '{"different":true}' }))).toEqual({
      inserted: false
    })
    expect(store.listBySlice('ORCA-S4')).toHaveLength(1)
  })

  it('genuinely different evidence for the same correlation_id + kind is a NEW row', () => {
    const { store } = open()
    store.insert(incident())
    expect(store.insert(incident({ id: 'inc_2', evidenceDigest: 'i'.repeat(64) }))).toEqual({
      inserted: true
    })
    expect(store.listBySlice('ORCA-S4')).toHaveLength(2)
  })

  it('hasOpenLifecycleIncident(correlationId) is true while unresolved, false once resolved', () => {
    const { store } = open()
    store.insert(incident())
    expect(store.hasOpenLifecycleIncident('corr_1')).toBe(true)
    store.resolve('inc_1', { resolvedAt: '2026-09-14T00:00:00Z', resolutionNote: 'operator cleared it' })
    expect(store.hasOpenLifecycleIncident('corr_1')).toBe(false)
  })

  it('resolve sets resolved_at/resolution_note and clears blocked, but never auto-fires from a sweep (manual-resolution contract only)', () => {
    const { store } = open()
    store.insert(incident())
    store.resolve('inc_1', { resolvedAt: '2026-09-14T00:00:00Z', resolutionNote: 'ok' })
    const row = store.listBySlice('ORCA-S4')[0]
    expect(row.resolvedAt).toBe('2026-09-14T00:00:00Z')
    expect(row.blocked).toBe(false)
  })

  it('all five §8.4 kinds are representable', () => {
    const { store } = open()
    const kinds: DispatchLifecycleIncidentRecord['kind'][] = [
      'process_identity_mismatch',
      'orphan_process_unverifiable',
      'worktree_finalization_conflict',
      'orphan_worktree_unverifiable',
      'post_closure_settlement_conflict'
    ]
    for (const [i, kind] of kinds.entries()) {
      store.insert(incident({ id: `inc_${i}`, kind, evidenceDigest: `${kind}`.padEnd(64, '0') }))
    }
    expect(store.listBySlice('ORCA-S4')).toHaveLength(kinds.length)
  })

  it('is the ONLY S4 table dropped + regenerated by a projection rebuild (§8.0, §8.8) — rebuild loses unresolved rows unless the sweep re-raises them', () => {
    const { db, store } = open()
    store.insert(incident())
    db.exec('DROP TABLE IF EXISTS dispatch_lifecycle_incident;')
    expect(store.listBySlice('ORCA-S4')).toHaveLength(0) // table dropped out from under a stale handle -> re-ensured empty
    migrateExecutionStore(db)
    expect(store.listBySlice('ORCA-S4')).toHaveLength(0)
  })
})
